### ISSUE TITLE
Android browser, Samsung s5 mini 

### ISSUE THREAD

**Issue by gogannes** [gogannes/makeweathergreatagain#9]
Funktioniert nicht. (trotz Parametern nur Anzeige der Startseite)

**Comment by daniel-sc** [comment]
Gibts dafür einen windows/online Simulator?
Welcher Browser/Version ist das?

**Comment by gogannes** [comment]
zum testing ein interessanter artikel (vieles selbstverständlich): https://www.mobilejoomla.com/blog/222-how-to-test-mobile-websites-on-desktop-best-emulators-and-tools.html

ich habe mal hier getestet: http://www.mobilephoneemulator.com/
allerdings wird dort selbst beim iphone 5 schon die start seite nicht korrekt dargestellt, daher wohl schwierig.

genaue broswer beschreibung kenne ich nicht.

**Comment by daniel-sc** [comment]
Ich habe mal bei www.browserstack.com nach einem kostenlosen Plan für uns als Open-Source Projekt angefragt..

**Comment by gogannes** [comment]
das problem tritt bei mir auch im internet explorer (v 11.0.9600.18525) auf. ich denke du kannst es mit deinem ie nachvollziehen.

in einer fürheren version (Merge pull request #6 from gogannes/revert-3-revert-2-master) hatten wir nicht diese probleme. könnte sein, dass die on-the-fly url-anpassung schuldig ist? 


zusätzlich muss man auch activeX zulassen was nicht gerade cool ist.. =/
![image](https://cloud.githubusercontent.com/assets/23582486/20519315/bc3d9aee-b0a2-11e6-9ee0-92d9c16ad0d7.png)

**Comment by gogannes** [comment]
korrektur: zusätzlich mussman auch activeX oder scripte zulassen (wenn damit javascript gemeint ist kommt man wohl nicht drum rum)

**Comment by daniel-sc** [comment]
Hm - das mit dem activeX ist in jedem Fall blöd - bei mir (v 11.0.9600.18499) tritt das aber nicht auf.
Aber dass alles net funzt ist bei mir beim IE auch der Fall - ich schau mir das mal an..

**Comment by daniel-sc** [comment]
IE 11 sollte jetzt laufen. @gogannes testest du auch bei dir nochmal (ggf. mit offenen F12 dev tools, um Fehler zu sehen)?

**Comment by gogannes** [comment]
Geht immer noch nicht. das kommt beim laden:

![image](https://cloud.githubusercontent.com/assets/23582486/20561635/c91d6aa4-b17f-11e6-8ebe-1e2ae1976012.png)
![image](https://cloud.githubusercontent.com/assets/23582486/20561678/068f424a-b180-11e6-9824-647c30092f3d.png)

**Comment by daniel-sc** [comment]
@gogannes Das Problem ist vermutlich "..is running in Compatitibility View.." d.h. dieser IE verhält sich nicht wie IE11 sondern wie irgendeine ältere Version..
Was ich nicht verstehe ist, warum er http://makeweathergreatagain.com als "intranet site" klassifiziert - kannst du das prüfen?

**Comment by gogannes** [comment]
Habe jetzt bei den Einstellungen ein bisschen rum probiert und es scheint jetzt zu laufen. Meine Bekannte hat auch bestätigt, dass es auf ihrem Handy jetzt geht.
